baseURL = "http://localhost:1313/blog/"
languageCode = "en-us"
title = "My digital brain"
theme = "roadster" # fork from mainroad
#theme = "mainroad" # original theme
themesDir = "themes"
publishDir = "public"

[Params]
schema = true # Enable Schema
readmore = true # Show "Read more" button in list if true
authorbox = false # Show authorbox at bottom of pages if true
toc = true # Enable Table of Contents
customCSS = ["css/custom.css"] # Include custom CSS files
post_meta = ["author", "date", "categories", "translations"]

